// Pricing data for atlantic.net
// 
// Supplied 11/19/2013 by atlantic.net staff; see http://www.atlantic.net/cloud-hosting/cloud-server-pricing

serverChoices.push({"region":"N. America","hourlyCost":0.005,"location":"Eastern-USA","provider":"Atlantic.Net","ramMB":256.0,"networkMbps":3,"flashMB":0,"cores":1.0,"serverType":"256MB","reservationType":"hourly","termMonths":0.0,"diskMB":10000.0,"term":"Hour","upfrontCost":0.0});
serverChoices.push({"region":"N. America","hourlyCost":0.0068,"location":"Eastern-USA","provider":"Atlantic.Net","ramMB":512.0,"networkMbps":3,"flashMB":0,"cores":1.0,"serverType":"512MB","reservationType":"hourly","termMonths":0.0,"diskMB":20000.0,"term":"Hour","upfrontCost":0.0});
serverChoices.push({"region":"N. America","hourlyCost":0.0136,"location":"Eastern-USA","provider":"Atlantic.Net","ramMB":1024.0,"networkMbps":3,"flashMB":0,"cores":1.0,"serverType":"1GB","reservationType":"hourly","termMonths":0.0,"diskMB":80000.0,"term":"Hour","upfrontCost":0.0});
serverChoices.push({"region":"N. America","hourlyCost":0.0273,"location":"Eastern-USA","provider":"Atlantic.Net","ramMB":2048.0,"networkMbps":3,"flashMB":0,"cores":1.0,"serverType":"2GB","reservationType":"hourly","termMonths":0.0,"diskMB":160000.0,"term":"Hour","upfrontCost":0.0});
serverChoices.push({"region":"N. America","hourlyCost":0.0547,"location":"Eastern-USA","provider":"Atlantic.Net","ramMB":4096.0,"networkMbps":3,"flashMB":0,"cores":2.0,"serverType":"4GB","reservationType":"hourly","termMonths":0.0,"diskMB":320000.0,"term":"Hour","upfrontCost":0.0});
serverChoices.push({"region":"N. America","hourlyCost":0.1095,"location":"Eastern-USA","provider":"Atlantic.Net","ramMB":8192.0,"networkMbps":3,"flashMB":0,"cores":4.0,"serverType":"8GB","reservationType":"hourly","termMonths":0.0,"diskMB":500000.0,"term":"Hour","upfrontCost":0.0});
serverChoices.push({"region":"N. America","hourlyCost":0.2190,"location":"Eastern-USA","provider":"Atlantic.Net","ramMB":16384.0,"networkMbps":3,"flashMB":0,"cores":4.0,"serverType":"16GB","reservationType":"hourly","termMonths":0.0,"diskMB":750000.0,"term":"Hour","upfrontCost":0.0});