serverChoices.push({ "provider": "Azure", "region": "US East", "location": "Virginia", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 14.88, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US East", "location": "Virginia", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 44.64, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US East", "location": "Virginia", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 89.28, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US East", "location": "Virginia", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 178.56, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US East", "location": "Virginia", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 357.12, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US East", "location": "Virginia", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 238.08, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US East", "location": "Virginia", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 476.16, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US East", "location": "Virginia", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 959.76, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure (MSDN)", "region": "US East", "location": "Virginia", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 14.88, "upfrontCost": 0.0, "hourlyCost": 0.01, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US East", "location": "Virginia", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 44.64, "upfrontCost": 0.0, "hourlyCost": 0.04, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US East", "location": "Virginia", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 89.28, "upfrontCost": 0.0, "hourlyCost": 0.08, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US East", "location": "Virginia", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 178.56, "upfrontCost": 0.0, "hourlyCost": 0.16, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US East", "location": "Virginia", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 357.12, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US East", "location": "Virginia", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 238.08, "upfrontCost": 0.0, "hourlyCost": 0.21, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US East", "location": "Virginia", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 476.16, "upfrontCost": 0.0, "hourlyCost": 0.42, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US East", "location": "Virginia", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 959.76, "upfrontCost": 0.0, "hourlyCost": 0.86, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure", "region": "US West", "location": "California", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 14.88, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US West", "location": "California", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 44.64, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US West", "location": "California", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 89.28, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US West", "location": "California", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 178.56, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US West", "location": "California", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 357.12, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US West", "location": "California", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 238.08, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US West", "location": "California", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 476.16, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US West", "location": "California", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 959.76, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure (MSDN)", "region": "US West", "location": "California", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 14.88, "upfrontCost": 0.0, "hourlyCost": 0.01, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US West", "location": "California", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 44.64, "upfrontCost": 0.0, "hourlyCost": 0.04, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US West", "location": "California", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 89.28, "upfrontCost": 0.0, "hourlyCost": 0.08, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US West", "location": "California", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 178.56, "upfrontCost": 0.0, "hourlyCost": 0.16, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US West", "location": "California", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 357.12, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US West", "location": "California", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 238.08, "upfrontCost": 0.0, "hourlyCost": 0.21, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US West", "location": "California", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 476.16, "upfrontCost": 0.0, "hourlyCost": 0.42, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US West", "location": "California", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 959.76, "upfrontCost": 0.0, "hourlyCost": 0.86, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

/*
Looks like these regions are not avaible right now

serverChoices.push({ "provider": "Azure", "region": "US North-central", "location": "Chicago", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 14.88, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US North-central", "location": "Chicago", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 44.64, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US North-central", "location": "Chicago", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 89.28, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US North-central", "location": "Chicago", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 178.56, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US North-central", "location": "Chicago", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 357.12, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US North-central", "location": "Chicago", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 238.08, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US North-central", "location": "Chicago", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 476.16, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US North-central", "location": "Chicago", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 959.76, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   


serverChoices.push({ "provider": "Azure", "region": "US South-central", "location": "San Antonio", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 14.88, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US South-central", "location": "San Antonio", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 44.64, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US South-central", "location": "San Antonio", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 89.28, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US South-central", "location": "San Antonio", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 178.56, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US South-central", "location": "San Antonio", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 357.12, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US South-central", "location": "San Antonio", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 238.08, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US South-central", "location": "San Antonio", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 476.16, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US South-central", "location": "San Antonio", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 959.76, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
*/

serverChoices.push({ "provider": "Azure", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 14.88, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 44.64, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 89.28, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 178.56, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 357.12, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 238.08, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 476.16, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 959.76, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure (MSDN)", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 14.88, "upfrontCost": 0.0, "hourlyCost": 0.01, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 44.64, "upfrontCost": 0.0, "hourlyCost": 0.04, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 89.28, "upfrontCost": 0.0, "hourlyCost": 0.08, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 178.56, "upfrontCost": 0.0, "hourlyCost": 0.16, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 357.12, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 238.08, "upfrontCost": 0.0, "hourlyCost": 0.21, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 476.16, "upfrontCost": 0.0, "hourlyCost": 0.42, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 959.76, "upfrontCost": 0.0, "hourlyCost": 0.86, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 14.88, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 44.64, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 89.28, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 178.56, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 357.12, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 238.08, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 476.16, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 959.76, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });

serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 14.88, "upfrontCost": 0.0, "hourlyCost": 0.01, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 44.64, "upfrontCost": 0.0, "hourlyCost": 0.04, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 89.28, "upfrontCost": 0.0, "hourlyCost": 0.08, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 178.56, "upfrontCost": 0.0, "hourlyCost": 0.16, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 357.12, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 238.08, "upfrontCost": 0.0, "hourlyCost": 0.21, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 476.16, "upfrontCost": 0.0, "hourlyCost": 0.42, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 959.76, "upfrontCost": 0.0, "hourlyCost": 0.86, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 14.88, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 44.64, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 89.28, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 178.56, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 357.12, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 238.08, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 476.16, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 959.76, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });

serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 14.88, "upfrontCost": 0.0, "hourlyCost": 0.01, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 44.64, "upfrontCost": 0.0, "hourlyCost": 0.04, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 89.28, "upfrontCost": 0.0, "hourlyCost": 0.08, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 178.56, "upfrontCost": 0.0, "hourlyCost": 0.16, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 357.12, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 238.08, "upfrontCost": 0.0, "hourlyCost": 0.21, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 476.16, "upfrontCost": 0.0, "hourlyCost": 0.42, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 959.76, "upfrontCost": 0.0, "hourlyCost": 0.86, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 14.88, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 44.64, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 89.28, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 178.56, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 357.12, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 238.08, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 476.16, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 959.76, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure (MSDN)", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 14.88, "upfrontCost": 0.0, "hourlyCost": 0.01, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 44.64, "upfrontCost": 0.0, "hourlyCost": 0.04, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 89.28, "upfrontCost": 0.0, "hourlyCost": 0.08, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 178.56, "upfrontCost": 0.0, "hourlyCost": 0.16, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 357.12, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 238.08, "upfrontCost": 0.0, "hourlyCost": 0.21, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 476.16, "upfrontCost": 0.0, "hourlyCost": 0.42, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 959.76, "upfrontCost": 0.0, "hourlyCost": 0.86, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure", "region": "South East Asia", "location": "Singapore", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 14.88, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "South East Asia", "location": "Singapore", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 44.64, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "South East Asia", "location": "Singapore", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 89.28, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "South East Asia", "location": "Singapore", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 178.56, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "South East Asia", "location": "Singapore", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 357.12, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "South East Asia", "location": "Singapore", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 238.08, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "South East Asia", "location": "Singapore", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 476.16, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "South East Asia", "location": "Singapore", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 959.76, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure (MSDN)", "region": "South East Asia", "location": "Singapore", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 14.88, "upfrontCost": 0.0, "hourlyCost": 0.01, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "South East Asia", "location": "Singapore", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 44.64, "upfrontCost": 0.0, "hourlyCost": 0.04, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "South East Asia", "location": "Singapore", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 89.28, "upfrontCost": 0.0, "hourlyCost": 0.08, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "South East Asia", "location": "Singapore", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 178.56, "upfrontCost": 0.0, "hourlyCost": 0.16, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "South East Asia", "location": "Singapore", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 357.12, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "South East Asia", "location": "Singapore", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 238.08, "upfrontCost": 0.0, "hourlyCost": 0.21, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "South East Asia", "location": "Singapore", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 476.16, "upfrontCost": 0.0, "hourlyCost": 0.42, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "South East Asia", "location": "Singapore", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 959.76, "upfrontCost": 0.0, "hourlyCost": 0.86, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
