// contact: @unknownexception
// Parsed from http://www.windowsazure.com/en-us/pricing/calculator/?scenario=virtual-machines
// with following script: 
// --------------------------------------------------------------------------------------
// var choisesJS = [];

// var regionsData = [
//     {regionName: 'US East', location: 'Virginia'}
//   , {regionName: 'US West', location: 'California'}
//   , {regionName: 'North Europe', location: 'Dublin, Ireland'}
//   , {regionName: 'West Europe', location: 'Amsterdam, Netherlands'}
//   , {regionName: 'East Asia', location: 'Hong Kong, China'}
//   , {regionName: 'South East Asia', location: 'Singapore'}
//   ];

// $.each(regionsData, function (i, region) {
  
//   var regionInfo = '"region": "' + region.regionName + '", "location": " ' + region.location + '"';
//   $('.buy-configure-virtual-machines-linux ul.selector-abbr li').each(
//     function (i, row) { 
    
//       var selector_name = $('.buy-configure-virtual-machines-linux ul.selector-name');
//       var hourlyCost = $(row).data('hourly');
//       var instanceClass = $(row).attr('class').replace(' active', '');
//       var instanceInfo = selector_name.find('.' + instanceClass).text();
//       var itype = /^(\w|\s)*/gmi;
//       var instanceType = itype.exec(instanceInfo)[0];
//       var instanceInfo = instanceInfo.replace(instanceType, '').split(', ');    
//       var instanceRamMB = instanceInfo[1].indexOf('MB') != -1?  instanceInfo[1].trim().replace('MB RAM','') : instanceInfo[1].trim().replace('GB RAM','') * 1024;
//       var instanceDiskMB = instanceInfo[2].trim().replace(')','').replace(',','').replace('GB Storage','') * 1024;
//       var instanceCores = instanceClass == "xs" ? 0.167 : instanceInfo[0].trim().replace('(','')[0];  
    

//       choisesJS.push('serverChoices.push({ "provider": "Azure", ' + regionInfo + ', "serverType": "' + instanceClass 
//         + '", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": ' + hourlyCost 
//         + ', "cores": ' + instanceCores + ', "ramMB": ' + instanceRamMB + ', "diskMB": ' + instanceDiskMB + ', "flashMB": 0.0, "networkMbps": 0.0 });' );   

//   });
// });

// console.log (choisesJS.join('\n'));
// --------------------------------------------------------------------------------------
// @sozercan added bizpark/msdn subscriptions with 33% price savings http://www.windowsazure.com/en-us/offers/ms-azr-0057p/ 


serverChoices.push({ "provider": "Azure", "region": "US East", "location": "Virginia", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores": 0.167, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US East", "location": "Virginia", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US East", "location": "Virginia", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US East", "location": "Virginia", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US East", "location": "Virginia", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US East", "location": "Virginia", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US East", "location": "Virginia", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US East", "location": "Virginia", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure (MSDN)", "region": "US East", "location": "Virginia", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.01, "cores": 0.167, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US East", "location": "Virginia", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.04, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US East", "location": "Virginia", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.08, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US East", "location": "Virginia", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.16, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US East", "location": "Virginia", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US East", "location": "Virginia", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.21, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US East", "location": "Virginia", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.42, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US East", "location": "Virginia", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.86, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure", "region": "US West", "location": "California", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores": 0.167, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US West", "location": "California", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US West", "location": "California", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US West", "location": "California", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US West", "location": "California", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US West", "location": "California", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US West", "location": "California", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US West", "location": "California", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure (MSDN)", "region": "US West", "location": "California", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.01, "cores":  0.167, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US West", "location": "California", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.04, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US West", "location": "California", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.08, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US West", "location": "California", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.16, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US West", "location": "California", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US West", "location": "California", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.21, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US West", "location": "California", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.42, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "US West", "location": "California", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.86, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

/*
Looks like these regions are not avaible right now

serverChoices.push({ "provider": "Azure", "region": "US North-central", "location": "Chicago", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US North-central", "location": "Chicago", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US North-central", "location": "Chicago", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US North-central", "location": "Chicago", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US North-central", "location": "Chicago", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US North-central", "location": "Chicago", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US North-central", "location": "Chicago", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US North-central", "location": "Chicago", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   


serverChoices.push({ "provider": "Azure", "region": "US South-central", "location": "San Antonio", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores": 1.0, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US South-central", "location": "San Antonio", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US South-central", "location": "San Antonio", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US South-central", "location": "San Antonio", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US South-central", "location": "San Antonio", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US South-central", "location": "San Antonio", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US South-central", "location": "San Antonio", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "US South-central", "location": "San Antonio", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
*/

serverChoices.push({ "provider": "Azure", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores":  0.167, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure (MSDN)", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.01, "cores":  0.167, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.04, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.08, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.16, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.21, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.42, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "North Europe", "location": "Dublin, Ireland", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.86, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores":  0.167, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });

serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.01, "cores": 0.167, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.04, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.08, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.16, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.21, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.42, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.86, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores": 0.167, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });

serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.01, "cores": 0.167, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.04, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.08, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.16, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.21, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.42, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "West Europe", "location": "Amsterdam, Netherlands", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.86, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores": 0.167, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure (MSDN)", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.01, "cores": 0.167, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.04, "cores": 0.167, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.08, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.16, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.21, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.42, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "East Asia", "location": "Hong Kong, China", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.86, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure", "region": "South East Asia", "location": "Singapore", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.02, "cores": 0.167, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "South East Asia", "location": "Singapore", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.06, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "South East Asia", "location": "Singapore", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.12, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "South East Asia", "location": "Singapore", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.24, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "South East Asia", "location": "Singapore", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.48, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "South East Asia", "location": "Singapore", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "South East Asia", "location": "Singapore", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.64, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure", "region": "South East Asia", "location": "Singapore", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 1.29, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   

serverChoices.push({ "provider": "Azure (MSDN)", "region": "South East Asia", "location": "Singapore", "serverType": "Extra small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.01, "cores": 0.167, "ramMB": 768.0, "diskMB": 20480.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "South East Asia", "location": "Singapore", "serverType": "Small VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.04, "cores": 1.0, "ramMB": 1792.0, "diskMB": 225000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "South East Asia", "location": "Singapore", "serverType": "Medium VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.08, "cores": 2.0, "ramMB": 1792.0, "diskMB": 501760.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "South East Asia", "location": "Singapore", "serverType": "Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.16, "cores": 4.0, "ramMB": 7168.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "South East Asia", "location": "Singapore", "serverType": "Extra Large VM", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.32, "cores": 8.0, "ramMB": 14336.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "South East Asia", "location": "Singapore", "serverType": "Memory Intensive VM - A5", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.21, "cores": 2.0, "ramMB": 14336.0, "diskMB": 490000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "South East Asia", "location": "Singapore", "serverType": "Memory Intensive VM - A6", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.42, "cores": 4.0, "ramMB": 28672.0, "diskMB": 1024000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
serverChoices.push({ "provider": "Azure (MSDN)", "region": "South East Asia", "location": "Singapore", "serverType": "Memory Intensive VM - A7", "reservationType": "hourly", "term": "Hour", "termMonths": 0.0, "upfrontCost": 0.0, "hourlyCost": 0.86, "cores": 8.0, "ramMB": 57344.0, "diskMB": 2048000.0, "flashMB": 0.0, "networkMbps": 0.0 });   
