serverChoices.push({
    "provider": "Brightbox Cloud",
    "region": "Europe",
    "location": "Manchester, UK",
    "serverType": "Standard Nano",
    "reservationType": "hourly",
    "term": "Hour",
    "termMonths": 0.0,
    "upfrontCost": 0.0,
    "hourlyCost": 0.024,
    "cores": 1,
    "ramMB": 512.0,
    "diskMB": 20480.0,
    "flashMB": 0.0,
    "networkMbps": 0.0
});
serverChoices.push({
    "provider": "Brightbox Cloud",
    "region": "Europe",
    "location": "Manchester, UK",
    "serverType": "Standard Mini",
    "reservationType": "hourly",
    "term": "Hour",
    "termMonths": 0.0,
    "upfrontCost": 0.0,
    "hourlyCost": 0.048,
    "cores": 2,
    "ramMB": 1024.0,
    "diskMB": 40960.0,
    "flashMB": 0.0,
    "networkMbps": 0.0
});
serverChoices.push({
    "provider": "Brightbox Cloud",
    "region": "Europe",
    "location": "Manchester, UK",
    "serverType": "Standard Small",
    "reservationType": "hourly",
    "term": "Hour",
    "termMonths": 0.0,
    "upfrontCost": 0.0,
    "hourlyCost": 0.097,
    "cores": 2,
    "ramMB": 2048.0,
    "diskMB": 81920.0,
    "flashMB": 0.0,
    "networkMbps": 0.0
});
serverChoices.push({
    "provider": "Brightbox Cloud",
    "region": "Europe",
    "location": "Manchester, UK",
    "serverType": "Standard Medium",
    "reservationType": "hourly",
    "term": "Hour",
    "termMonths": 0.0,
    "upfrontCost": 0.0,
    "hourlyCost": 0.19,
    "cores": 4,
    "ramMB": 4096.0,
    "diskMB": 163840.0,
    "flashMB": 0.0,
    "networkMbps": 0.0
});
serverChoices.push({
    "provider": "Brightbox Cloud",
    "region": "Europe",
    "location": "Manchester, UK",
    "serverType": "Standard Large",
    "reservationType": "hourly",
    "term": "Hour",
    "termMonths": 0.0,
    "upfrontCost": 0.0,
    "hourlyCost": 0.387,
    "cores": 4,
    "ramMB": 8192.0,
    "diskMB": 327680.0,
    "flashMB": 0.0,
    "networkMbps": 0.0
});
serverChoices.push({
    "provider": "Brightbox Cloud",
    "region": "Europe",
    "location": "Manchester, UK",
    "serverType": "Standard XL",
    "reservationType": "hourly",
    "term": "Hour",
    "termMonths": 0.0,
    "upfrontCost": 0.0,
    "hourlyCost": 0.77,
    "cores": 4,
    "ramMB": 16384.0,
    "diskMB": 655360.0,
    "flashMB": 0.0,
    "networkMbps": 0.0
});
serverChoices.push({
    "provider": "Brightbox Cloud",
    "region": "Europe",
    "location": "Manchester, UK",
    "serverType": "Standard XL",
    "reservationType": "hourly",
    "term": "Hour",
    "termMonths": 0.0,
    "upfrontCost": 0.0,
    "hourlyCost": 1.547,
    "cores": 4,
    "ramMB": 32768.0,
    "diskMB": 1310720.0,
    "flashMB": 0.0,
    "networkMbps": 0.0
});
serverChoices.push({
    "provider": "Brightbox Cloud",
    "region": "Europe",
    "location": "Manchester, UK",
    "serverType": "High IO Nano",
    "reservationType": "hourly",
    "term": "Hour",
    "termMonths": 0.0,
    "upfrontCost": 0.0,
    "hourlyCost": 0.032,
    "cores": 2,
    "ramMB": 512.0,
    "diskMB": 20480.0,
    "flashMB": 0.0,
    "networkMbps": 0.0
});
serverChoices.push({
    "provider": "Brightbox Cloud",
    "region": "Europe",
    "location": "Manchester, UK",
    "serverType": "High IO Mini",
    "reservationType": "hourly",
    "term": "Hour",
    "termMonths": 0.0,
    "upfrontCost": 0.0,
    "hourlyCost": 0.064,
    "cores": 4,
    "ramMB": 1024.0,
    "diskMB": 40960.0,
    "flashMB": 0.0,
    "networkMbps": 0.0
});
serverChoices.push({
    "provider": "Brightbox Cloud",
    "region": "Europe",
    "location": "Manchester, UK",
    "serverType": "High IO Small",
    "reservationType": "hourly",
    "term": "Hour",
    "termMonths": 0.0,
    "upfrontCost": 0.0,
    "hourlyCost": 0.129,
    "cores": 4,
    "ramMB": 2048.0,
    "diskMB": 81920.0,
    "flashMB": 0.0,
    "networkMbps": 0.0
});
serverChoices.push({
    "provider": "Brightbox Cloud",
    "region": "Europe",
    "location": "Manchester, UK",
    "serverType": "High IO Medium",
    "reservationType": "hourly",
    "term": "Hour",
    "termMonths": 0.0,
    "upfrontCost": 0.0,
    "hourlyCost": 0.257,
    "cores": 8,
    "ramMB": 4096.0,
    "diskMB": 163840.0,
    "flashMB": 0.0,
    "networkMbps": 0.0
});
serverChoices.push({
    "provider": "Brightbox Cloud",
    "region": "Europe",
    "location": "Manchester, UK",
    "serverType": "High IO Large",
    "reservationType": "hourly",
    "term": "Hour",
    "termMonths": 0.0,
    "upfrontCost": 0.0,
    "hourlyCost": 0.516,
    "cores": 8,
    "ramMB": 8192.0,
    "diskMB": 327680.0,
    "flashMB": 0.0,
    "networkMbps": 0.0
});
serverChoices.push({
    "provider": "Brightbox Cloud",
    "region": "Europe",
    "location": "Manchester, UK",
    "serverType": "High IO XL",
    "reservationType": "hourly",
    "term": "Hour",
    "termMonths": 0.0,
    "upfrontCost": 0.0,
    "hourlyCost": 1.032,
    "cores": 8,
    "ramMB": 16384.0,
    "diskMB": 655360.0,
    "flashMB": 0.0,
    "networkMbps": 0.0
});
serverChoices.push({
    "provider": "Brightbox Cloud",
    "region": "Europe",
    "location": "Manchester, UK",
    "serverType": "High IO XL",
    "reservationType": "hourly",
    "term": "Hour",
    "termMonths": 0.0,
    "upfrontCost": 0.0,
    "hourlyCost": 2.063,
    "cores": 8,
    "ramMB": 32768.0,
    "diskMB": 1310720.0,
    "flashMB": 0.0,
    "networkMbps": 0.0
});
