// Auto-generated by CloudPriceFetcher.java

serverChoices.push({"region":"N. America","hourlyCost":15.0,"location":"Maryland","provider":"Other","ramMB":0.0,"networkMbps":0.0,"flashMB":0.0,"cores":0.001,"serverType":"ENIAC","reservationType":"purchase","termMonths":98.0,"diskMB":0.0,"term":"3 Years","upfrontCost":5900000.0});
serverChoices.push({"region":"Asia","hourlyCost":2400.0,"location":"Guangzhou, China","provider":"Other","ramMB":1.441792E9,"networkMbps":0.0,"flashMB":0.0,"cores":3120000.0,"serverType":"Tianhe-2","reservationType":"purchase","termMonths":36.0,"diskMB":1.33143986176E10,"term":"3 Years","upfrontCost":3.9E8});
